### ISSUE TITLE
Behavior on MacOS is untested

### ISSUE THREAD

**Issue by s-m-e** [pleiszenburg/zugbruecke#16]
Testers needed.

---

EDIT (2018-03-05): Confirmed to work on Mac OS X out of the box with Wine installed. Support for CI testing on Mac OS must be added next.

**Comment by jtlz2** [comment]
@s-m-e I'm happy to test :)

So far:

```
python -c "from zugbruecke import windll, c_float"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/__init__.py", line 131, in <module>
    from ._wrapper_ import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/_wrapper_.py", line 57, in <module>
    from .core.session_client import session_client_class
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/session_client.py", line 50, in <module>
    from .wineenv import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/wineenv.py", line 38, in <module>
    import urllib.request
ImportError: No module named request
```

Is this a 2 vs 3 issue, or a genuine bug in that urllib has no request module?

**Comment by jtlz2** [comment]
@s-m-e I'm happy to test - so far so good:

    python3 -c "from zugbruecke import windll, c_float"

gives no output :)

**Comment by s-m-e** [comment]
@jtlz2 Thanks for your interest and your test :)

For a full test, you need **Python 3**, Wine and a Windows DLL you can call into. If you do not have one around, you can call onto one of the DLLs, which are shipped with Wine. The example in the [readme file](https://github.com/pleiszenburg/zugbruecke/blob/master/README.rst) is about the most trivial test and should work out of the box - once the package is installed via `pip install zugbruecke`:

```from zugbruecke import cdll, c_double
dll_pow = cdll.msvcrt.pow
dll_pow.argtypes = (c_double, c_double)
dll_pow.restype = c_double
print('You should expect "1024.0" to show up here: "%.1f".' % dll_pow(2.0, 10.0))
```

The above would call into `msvcrt.dll`, which is offered as a part of Wine.

You can also run the test suite of the project. For this, you would first have to follow the [guidelines for first time setup for developers](https://github.com/pleiszenburg/zugbruecke/blob/master/CONTRIBUTING.rst#first-time-setup). Secondly, you do need a mingw cross-compiler for this as the test suite builds its own Windows DLL for testing. You can trigger the build process with `make dll`. At last, once the development environment is installed, you simply run `make test`.

If you need any help, I am more than happy to assist. Just let me know what I can do. I just realized that the contributing files needs a bit of an update ...

**Comment by jtlz2** [comment]
@s-m-e Thanks in advance for all assistance - this will be super-useful to me if we can get it up-and-running.

I've got this far now:

```
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from zugbruecke import windll, c_float
>>> simple_demo_routine = windll.LoadLibrary('demo_dll.dll').simple_demo_routine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/_wrapper_.py", line 183, in WinDLL
    'mode': mode, 'use_errno': use_errno, 'use_last_error': use_last_error
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 123, in load_library
    self.__init_stage_2__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 284, in __init_stage_2__
    self.__start_ctypes_client__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 350, in __start_ctypes_client__
    raise # TODO
RuntimeError: No active exception to reraise
```

**Comment by jtlz2** [comment]
@s-m-e Apologies - I was running off the other demo [example](http://zugbruecke.readthedocs.io/en/latest/examples.html)

The code can't find `msvcrt`

>>> dll_pow = cdll.msvcrt.pow
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/_wrapper_.py", line 164, in CDLL
    'mode': mode, 'use_errno': use_errno, 'use_last_error': use_last_error
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 123, in load_library
    self.__init_stage_2__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 284, in __init_stage_2__
    self.__start_ctypes_client__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 350, in __start_ctypes_client__
    raise # TODO
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/_wrapper_.py", line 172, in CDLL
    return ctypes_CDLL_class(name, mode, handle, use_errno, use_last_error)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(msvcrt, 6): image not found

**Comment by s-m-e** [comment]
I just ran the following in a clean environment:

```
>>> import zugbruecke as ctypes
>>> msvcrt = ctypes.cdll.LoadLibrary('msvcrt.dll')
>>> dll_pow = msvcrt.pow
>>> dll_pow.argtypes = (ctypes.c_double, ctypes.c_double)
>>> dll_pow.restype = ctypes.c_double
>>> print('You should expect "1024.0" to show up here: "%.1f".' % dll_pow(2.0, 10.0))
You should expect "1024.0" to show up here: "1024.0".
```

Notice that I loaded the dll in a slightly different way: `ctypes.cdll.LoadLibrary('msvcrt.dll')`. Could you try that? 

You can also verify that the dll exists. In my case, I can do the following:

```
me@box:~> cd ~/.zugbruecke/
me@box:~/.zugbruecke> find . | grep -i msvcrt
./win32-wine/drive_c/windows/system32/msvcrt.dll
./win32-wine/drive_c/windows/system32/msvcrt20.dll
./win32-wine/drive_c/windows/system32/msvcrt40.dll
./win32-wine/drive_c/windows/system32/msvcrtd.dll
./_win32-wine/drive_c/windows/system32/msvcrt.dll
./_win32-wine/drive_c/windows/system32/msvcrt20.dll
./_win32-wine/drive_c/windows/system32/msvcrt40.dll
./_win32-wine/drive_c/windows/system32/msvcrtd.dll
```

The module should create a folder named `.zugbruecke` in your home folder (`~` or `$HOME`). I am not entirely sure how this looks like on Mac OS. In this folder, you should find the wine profile folder named `win32-wine`. This is where Wine stores its fake `C:` drive ... 

As for the `demo_dll.dll` file - if you can not compile it yourself (mingw is tricky ...), I can shoot it to you by email.

**Comment by s-m-e** [comment]
@jtlz2 You can also try loading it from its absolute fake path:
```
msvcrt = ctypes.cdll.LoadLibrary('C:\\windows\\sysytem32\\msvcrt.dll')
```

**Comment by jtlz2** [comment]
@s-m-e OK good so the dll is there:

```
cd ~/.zugbruecke/
find . | grep -i msvcrt
./win32-wine/drive_c/windows/system32/msvcrt40.dll
./win32-wine/drive_c/windows/system32/msvcrtd.dll
./win32-wine/drive_c/windows/system32/msvcrt20.dll
./win32-wine/drive_c/windows/system32/msvcrt.dll
```

Permissions (am running python3 as root) (currently -rw-r--r--)?

This didn't work:

```
msvcrt = ctypes.cdll.LoadLibrary('C:\\windows\\system32\\msvcrt.dll')
```

**Comment by jtlz2** [comment]
@s-m-e The following (non-fake path) gave:

```
>>> msvcrt = ctypes.cdll.LoadLibrary('./win32-wine/drive_c/windows/system32/msvcrt.dll')
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/_wrapper_.py", line 164, in CDLL
    'mode': mode, 'use_errno': use_errno, 'use_last_error': use_last_error
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 123, in load_library
    self.__init_stage_2__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 284, in __init_stage_2__
    self.__start_ctypes_client__()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/core/session_client.py", line 350, in __start_ctypes_client__
    raise # TODO
RuntimeError: No active exception to reraise

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zugbruecke/_wrapper_.py", line 172, in CDLL
    return ctypes_CDLL_class(name, mode, handle, use_errno, use_last_error)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(./win32-wine/drive_c/windows/system32/msvcrt.dll, 6): no suitable image found.  Did find:
	./win32-wine/drive_c/windows/system32/msvcrt.dll: file too short
	./win32-wine/drive_c/windows/system32/msvcrt.dll: stat() failed with errno=61
```

**Comment by s-m-e** [comment]
@jtlz2 Ok, I just looked at your trace-backs more carefully. For whatever reason, in your case, the `zugbruecke` module fails to start the Windows Python interpreter on top of Wine. This is the real showstopper. It does not even attempt to load the DLL. The idea is that you have two Python interpreters running: Your regular one on top of your Unix, i.e. OSX, and a Windows version on top of Wine, responsible for calling into DLLs. The latter is not even starting. 

You can debug it like this: Place a file named `.zugbruecke.json` in `~/.zugbruecke/`. Write the following into it:
```
{"log_level": 100}
```

Now try again. In my case, it looks like this:

```
user@box:~/Desktop/zugtest> python3
Python 3.6.4 (default, Feb 27 2018, 18:16:59) 
[GCC 4.8.5] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zugbruecke as ctypes
(1520242473.66/28bbdc36) UNIX o: [session-client] STARTING (STAGE 1) ...
(1520242473.66/28bbdc36) UNIX o: [session-client] Configured Wine-Python version is 3.5.3 for win32.
(1520242473.66/28bbdc36) UNIX o: [session-client] Log socket port: 32959.
(1520242473.66/28bbdc36) UNIX o: [session-client] STARTED (STAGE 1).
>>> msvcrt = ctypes.cdll.LoadLibrary('C:\\windows\\sysytem32\\msvcrt.dll')
(1520242476.43/28bbdc36) UNIX o: [session-client] STARTING (STAGE 2) ...
(1520242476.43/28bbdc36) UNIX o: [interpreter] STARTING ...
(1520242476.43/28bbdc36) UNIX o: [interpreter] Command: wine /home/user/.zugbruecke/win32-python3.5.3/python.exe /home/user/Desktop/zugtest/env/lib/python3.6/site-packages/zugbruecke/_server_.py --id 28bbdc36 --port_socket_ctypes 59895 --port_socket_log_main 32959 --log_level 100 --logwrite 0
(1520242476.44/28bbdc36) UNIX o: [interpreter] Started with PID 18018.
(1520242476.44/28bbdc36) UNIX o: [interpreter] Logging threads started.
(1520242476.44/28bbdc36) UNIX o: [interpreter] STARTED.
(1520242476.44/28bbdc36) UNIX o: [session-client] ctypes client connecting ...
(1520242477.17/28bbdc36) UNIX e: [P] fixme:msvcrt:_configure_wide_argv (1) stub
(1520242477.17/28bbdc36) UNIX e: [P] fixme:msvcrt:_initialize_wide_environment stub
(1520242477.24/28bbdc36) UNIX e: [P] err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
(1520242477.32/28bbdc36) UNIX e: [P] err:winediag:xrandr12_init_modes Broken NVIDIA RandR detected, falling back to RandR 1.0. Please consider using the Nouveau driver instead.
(1520242477.46/28bbdc36) WINE o: [session-server] STARTING ...
(1520242477.50/28bbdc36) WINE o: [mp-server] STARTING ...
(1520242477.50/28bbdc36) WINE o: [mp-server] Log attached.
(1520242477.50/28bbdc36) WINE o: [mp-server] STARTED.
(1520242477.50/28bbdc36) WINE o: [session-server] ctypes server is listening on port 59895.
(1520242477.50/28bbdc36) WINE o: [session-server] STARTED.
(1520242477.50/28bbdc36) WINE o: [session-server] Serve forever ...
(1520242477.56/28bbdc36) UNIX o: [session-client] ... connected (after 1.12 seconds & 107 attempts).
(1520242477.56/28bbdc36) UNIX o: [session-client] STARTED (STAGE 2).
(1520242477.56/28bbdc36) UNIX o: [session-client] Trying to access DLL "C:\windows\sysytem32\msvcrt.dll" of type "cdll" ...
(1520242477.56/28bbdc36) WINE o: [session-server] Attaching to DLL file "C:\windows\sysytem32\msvcrt.dll" with calling convention "cdll" ...
(1520242477.56/28bbdc36) WINE o: [session-server] ... done.
(1520242477.56/28bbdc36) UNIX o: [session-client] ... touched and added to list.
>>> 
```

**Comment by s-m-e** [comment]
@jtlz2 You can also test something more basic - whether or not the Windows Python interpreter can actually start. For this, you have to configure the log level back to 0 (or remove / rename `.zugbruecke.json`). Then, you can try the following:

```
user@box:~/Desktop/zugtest> wine-python 
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/etc/pythonstart", line 7, in <module>
    import readline
ImportError: No module named 'readline'
>>> import sys
>>> sys.platform
'win32'
>>> 
```

The `readline` error is expected. Otherwise, the Python interpreter should work just fine.

**Comment by jtlz2** [comment]
@s-m-e Excellent - nice interface BTW.

I think the problem was actually my over-cautious `sudo python3` rather than just `python3`:

```
$ python3
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import zugbruecke as ctypes
(1520245696.80/d141a8ca) UNIX o: [session-client] STARTING (STAGE 1) ...
(1520245696.80/d141a8ca) UNIX o: [session-client] Configured Wine-Python version is 3.5.3 for win32.
(1520245696.80/d141a8ca) UNIX o: [session-client] Log socket port: 55025.
(1520245696.80/d141a8ca) UNIX o: [session-client] STARTED (STAGE 1).
>>> msvcrt = ctypes.cdll.LoadLibrary('C:\\windows\\system32\\msvcrt.dll')
(1520245705.34/d141a8ca) UNIX o: [session-client] STARTING (STAGE 2) ...
(1520245705.34/d141a8ca) UNIX o: [interpreter] STARTING ...
(1520245705.34/d141a8ca) UNIX o: [interpreter] Command: wine /Users/jtlz2/.zugbruecke/win32-python3.5.3/python.exe /usr/local/lib/python3.6/site-packages/zugbruecke/_server_.py --id d141a8ca --port_socket_ctypes 55033 --port_socket_log_main 55025 --log_level 100 --logwrite 0
(1520245705.35/d141a8ca) UNIX o: [interpreter] Started with PID 81611.
(1520245705.35/d141a8ca) UNIX o: [interpreter] Logging threads started.
(1520245705.35/d141a8ca) UNIX o: [interpreter] STARTED.
(1520245705.35/d141a8ca) UNIX o: [session-client] ctypes client connecting ...
(1520245707.90/d141a8ca) UNIX e: [P] 0009:fixme:msvcrt:_configure_wide_argv (1) stub
(1520245707.90/d141a8ca) UNIX e: [P] 0009:fixme:msvcrt:_initialize_wide_environment stub
(1520245708.51/d141a8ca) UNIX e: [P] 0009:fixme:winsock:set_dont_fragment IP_DONTFRAGMENT for IPv4 not supported in this platform
(1520245708.52/d141a8ca) WINE o: [session-server] STARTING ...
(1520245708.52/d141a8ca) WINE o: [mp-server] STARTING ...
(1520245708.52/d141a8ca) WINE o: [mp-server] Log attached.
(1520245708.52/d141a8ca) WINE o: [mp-server] STARTED.
(1520245708.52/d141a8ca) WINE o: [session-server] ctypes server is listening on port 55033.
(1520245708.52/d141a8ca) WINE o: [session-server] STARTED.
(1520245708.52/d141a8ca) WINE o: [session-server] Serve forever ...
(1520245708.55/d141a8ca) UNIX o: [session-client] ... connected (after 3.20 seconds & 28 attempts).
(1520245708.55/d141a8ca) UNIX o: [session-client] STARTED (STAGE 2).
(1520245708.55/d141a8ca) UNIX o: [session-client] Trying to access DLL "C:\windows\system32\msvcrt.dll" of type "cdll" ...
(1520245708.55/d141a8ca) WINE o: [session-server] Attaching to DLL file "C:\windows\system32\msvcrt.dll" with calling convention "cdll" ...
(1520245708.55/d141a8ca) WINE o: [session-server] ... done.
(1520245708.55/d141a8ca) UNIX o: [session-client] ... touched and added to list.
>>> 
```

For your second test, wine-python is calling python2:

```
$ wine-python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/__init__.py", line 131, in <module>
    from ._wrapper_ import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/_wrapper_.py", line 57, in <module>
    from .core.session_client import session_client_class
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/session_client.py", line 50, in <module>
    from .wineenv import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/wineenv.py", line 38, in <module>
    import urllib.request
ImportError: No module named request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/__init__.py", line 131, in <module>
    from ._wrapper_ import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/_wrapper_.py", line 57, in <module>
    from .core.session_client import session_client_class
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/session_client.py", line 50, in <module>
    from .wineenv import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/wineenv.py", line 38, in <module>
    import urllib.request
ImportError: No module named request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/__init__.py", line 131, in <module>
    from ._wrapper_ import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/_wrapper_.py", line 57, in <module>
    from .core.session_client import session_client_class
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/session_client.py", line 50, in <module>
    from .wineenv import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/wineenv.py", line 38, in <module>
    import urllib.request
ImportError: No module named request
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/__init__.py", line 131, in <module>
    from ._wrapper_ import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/_wrapper_.py", line 57, in <module>
    from .core.session_client import session_client_class
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/session_client.py", line 50, in <module>
    from .wineenv import (
  File "/anaconda2/lib/python2.7/site-packages/zugbruecke/core/wineenv.py", line 38, in <module>
    import urllib.request
ImportError: No module named request
wine: WINEARCH set to invalid value '', it must be either win32 or win64.
```

What's the best way to fix this? (I am loathe to abandon python2 for good :\ )

**Comment by jtlz2** [comment]
@s-m-e Excellent! This works:

```
>>> import zugbruecke as ctypes
>>> msvcrt = ctypes.cdll.LoadLibrary('msvcrt.dll')
>>> dll_pow = msvcrt.pow
>>> dll_pow.argtypes = (ctypes.c_double, ctypes.c_double)
>>> dll_pow.restype = ctypes.c_double
>>> print('You should expect "1024.0" to show up here: "%.1f".' % dll_pow(2.0, 10.0))
You should expect "1024.0" to show up here: "1024.0".
```

The DLL I need to wrap is relatively bespoke, and I am not that familiar with ctypes in fact (have used CFFI though) - what is a good intermediate/next step for me to try?

**Comment by s-m-e** [comment]
@jtlz2 Cool :) In terms of `sudo` ... [I should make the warning even more obvious](https://github.com/pleiszenburg/zugbruecke#security), I guess.

Fixing the latter - in my environment, the `python` command always points to `python3`, which is why I overlooked this case - sry. It's three files I'd have to patch (in your case probably located in `/usr/local/bin`, named `wine-python`, `wine-pip` and `wine-pytest`). Those are simple bash scripts. You'd basically have to swap all `python -c` strings with `python3 -c`, if you want to do this yourself. I'll try to push a fix to github and pypi probably tonight.

ctypes: The best tutorial is happens to be its [documentation](https://docs.python.org/3/library/ctypes.html). It offers lots of examples right at the beginning.

**Comment by s-m-e** [comment]
@jtlz2 **Mac OS X support is hereby confirmed**, I suppose. Thanks a lot for testing. 

With respect to your DLL, feel free to open up a separate issue and post as much information on it as you can / want - most importantly any header files you might have. I can help you from there. Things become a bit tricky with `zugbruecke` if you're using more complicated structure types and pointers, but this can usually be solved.

**Comment by jtlz2** [comment]
@s-m-e Huge thanks - and speedy response much appreciated

No no, I saw that warning on a reread - my bad :)

I'm trying to do `make test` and running into the 2 vs 3 issue - a fix would be great but in the meantime I'll hack it myself yes.

This is great - no problem re testing - happy to help and looking forward to exploring some more.

I'll have a crack at the DLL and get back to you asap - thanks so much in advance.

**Comment by jtlz2** [comment]
@s-m-e Is it OK if I email you rather?

**Comment by s-m-e** [comment]
@jtlz2 [Sure.](http://www.pleiszenburg.de/#contact)

**Comment by s-m-e** [comment]
I am closing this issue as Mac OS X support has been confirmed :)
