### ISSUE TITLE
ZB misses ctypes exception: File "_ctypes/callbacks.c", line 234, in 'calling callback function'

### ISSUE THREAD

**Issue by jtlz2** [pleiszenburg/zugbruecke#38]
I've managed to get `ctypes` to throw an exception, but it's not trapped by ZB (should it be?):

(1522065500.92/c17f30d6) WINE o: {'d': 0, 'f': [], 'g': 2, 'n': None, 'p': False, 's': True, 't': 'c_byte'}
(1522065500.92/c17f30d6) UNIX o: [routine-client] ... configured. Proceeding ...
(1522065500.92/c17f30d6) UNIX o: [routine-client] ... parameters are "(<__main__.A object at 0x10443cb70>, <__main__.B object at 0x1044106a8>, <__main__.C object at 0x1044109d8>)". Packing and pushing to server ...
(1522065500.92/c17f30d6) WINE o: [routine-server] Trying call routine "func" ...
(1522065500.92/c17f30d6) WINE o: [callback-server] Trying to call callback routine "func_104cf9048" ...
(1522065500.92/c17f30d6) WINE o: [callback-server] ... parameters are "(None, 1363236)". Packing and pushing to client ...
(1522065500.92/c17f30d6) UNIX o: [callback-client] Trying to call callback routine "func_104cf9048" ...
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
TypeError: __init__ expected at most 1 arguments, got 2
(1522065500.92/c17f30d6) UNIX o: [callback-client] ... done.
(1522065500.92/c17f30d6) WINE o: [callback-server] ... received feedback from client, unpacking ...
(1522065500.92/c17f30d6) WINE o: [callback-server] ... unpacked, return.
(1522065500.92/c17f30d6) WINE o: [routine-server] ... failed!
(1522065500.92/c17f30d6) WINE e: Traceback (most recent call last):
(1522065500.92/c17f30d6) WINE e:   File "Z:\usr\local\lib\python3.6\site-packages\zugbruecke\core\routine_server.py", line 95, in __call__
(1522065500.92/c17f30d6) WINE e:     return_value = self.handler(*tuple(args_list))
(1522065500.92/c17f30d6) WINE e: OSError: exception: access violation reading 0x00000008
(1522065500.92/c17f30d6) UNIX o: [routine-client] ... received feedback from server, unpacking & syncing arguments ...
Traceback (most recent call last):
  File "./func.py", line 1329, in <module>
    ret=main()
  File "./func.py", line 1153, in main
    status=func(a,b,c)
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/routine_client.py", line 129, in __call__
    self.data.arg_list_unpack(return_dict['args'], self.argtypes_d),
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/data/contents.py", line 75, in arg_list_unpack
    return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/data/contents.py", line 75, in <listcomp>
    return [self.__unpack_item__(a[1], d) for a, d in zip(args_package_list, argtypes_list)]
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/data/contents.py", line 345, in __unpack_item__
    arg_rebuilt = self.__unpack_item_struct__(arg_raw, arg_def_dict)
  File "/usr/local/lib/python3.6/site-packages/zugbruecke/core/data/contents.py", line 467, in __unpack_item_struct__
    self.__unpack_item__(field_arg[1], field_def_dict) # parameter value
TypeError: expected FunctionType instance, got NoneType
(1522065500.93/c17f30d6) UNIX o: [session-client] TERMINATING ...
(1522065500.93/c17f30d6) UNIX o: [session-client] Waiting for session-server be down ...
(1522065500.93/c17f30d6) UNIX o: [session-client] ... session server is down (after 0.00 seconds).
(1522065500.93/c17f30d6) WINE o: [mp-server] TERMINATING ...
(1522065500.93/c17f30d6) WINE o: [session-server] TERMINATING ...
(1522065500.93/c17f30d6) WINE o: [session-server] TERMINATED.
(1522065500.93/c17f30d6) WINE o: [mp-server] TERMINATED.
(1522065500.93/c17f30d6) UNIX o: [interpreter] TERMINATING ...
(1522065500.93/c17f30d6) UNIX o: [interpreter] Joining logging thread "out" ...
(1522065501.93/c17f30d6) UNIX o: [interpreter] Joining logging thread "err" ...
(1522065502.93/c17f30d6) UNIX o: [interpreter] Logging threads joined or timed out.
(1522065502.93/c17f30d6) UNIX o: [interpreter] TERMINATED.
(1522065502.93/c17f30d6) UNIX o: [session-client] TERMINATED.

The reason for the mismatch in the number of arguments was to persuade the callback function `G` (see #35) not to crash ZB even earlier.

**Comment by s-m-e** [comment]
I lazily leave most of the exception trapping on the Unix side to the Python interpreter, but you're right, I should catch them in a more consistent manner.
