### ISSUE TITLE
import error in devel version

### ISSUE THREAD

**Issue by susnicek** [pleiszenburg/zugbruecke#80]
Dear developers of zugbruecke,
while the version 0.0.15 of zugbruecke works well for me, the development version 0.1.0 shows the following error with call `importzugbruecke.ctypes as ctypes` :

`>>> import zugbruecke.ctypes as ctypes
/home/xxx/Applications/python_env/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/Applications/python_env/lib/python3.10/site-packages/zugbruecke/ctypes/__init__.py", line 44, in <module>
    _session = _CtypesSession()
  File "/home/xxx/Applications/python_env/lib/python3.10/site-packages/zugbruecke/core/session.py", line 129, in __init__
    self._current_session = SessionClient(config=Config(**kwargs))
  File "/home/xxx/Applications/python_env/lib/python3.10/site-packages/zugbruecke/core/session_client.py", line 117, in __init__
    env.ensure()
  File "/home/xxx/Applications/python_env/lib/python3.10/site-packages/wenv/_core/env.py", line 238, in ensure
    self.setup_pip()
  File "/home/xxx/Applications/python_env/lib/python3.10/site-packages/wenv/_core/env.py", line 439, in setup_pip
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'wenv'` 

This error appears in fresh python virtual enviroment as well as with zuegbruecke installed in system python struccture. Any idea what to do?
My OS is: Debian sid: SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux
My Python is: Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0]

Bests, susnicek

**Comment by s-m-e** [comment]
I split the package into two parts a while ago. Most of the plumbing related to `Wine` is handled by [wenv](https://github.com/pleiszenburg/wenv) now. You need to install its latest development version, too. I am "a little" overdue with publishing new releases for both packages ...

**Comment by melvyn2** [comment]
I had the same error due to my user-local pip `bin` directory not being in `PATH`. This package should probably call it by using `python -m wenv` instead, but in the mean time, try adding the location of pip's `bin` directory to your path.

**Comment by s-m-e** [comment]
I touched a fair bit of related code recently, as part of today's upcoming release of v0.1.0. If possible, please test it and let me know of the error persists.

**Comment by s-m-e** [comment]
Is this issue still present?

**Comment by melvyn2** [comment]
Nope, still the same error if `wenv` is not in the path.
