### ISSUE TITLE
TypeError: one character bytes, bytearray or integer expected

### ISSUE THREAD

**Issue by ghost** [pleiszenburg/zugbruecke#98]
First of all, thank you for your wonderful project.

I discovered this project when I wanted to run the dll module under Linux, which is only available for Windows 32 bit

The module I am trying to use has title errors.

https://github.com/Na-x4/AquesTalk-python
An error occurred when I ran this module replacing ctypes with your project

```python
Traceback (most recent call last):
  File "/home/ubuntu/aquestalk-server/main.py", line 4, in <module>
    wav = aq.synthe_raw('あ')
  File "/home/ubuntu/aquestalk-server/aquestalk/aquestalk.py", line 118, in synthe_raw
    c_wav, size = self._synthe(koe, speed)
  File "/home/ubuntu/aquestalk-server/aquestalk/aquestalk.py", line 155, in _synthe
    c_wav = self._dll.AquesTalk_Synthe(koe.encode(), speed, ctypes.byref(c_size))
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/zugbruecke/core/routine_client.py", line 131, in __call__
    return_package = self._call_on_server(packed_args, packed_mempkgs)
  File "/home/ubuntu/.pyenv/versions/3.10.12/lib/python3.10/site-packages/zugbruecke/core/rpc.py", line 74, in call_rpc_server
    raise result
TypeError: one character bytes, bytearray or integer expected
```

This module does Japanese Text to speech.
When an error occurs from the dll, it returns only an error code and no audio data, so it can run normally, but when you enter the correct input and the dll returns audio data, an error occurs.

**Comment by s-m-e** [comment]
[This line](https://github.com/Na-x4/AquesTalk-python/blob/d5a13f67b35af7028bc7bc06da46a0fbcc0261e0/aquestalk/aquestalk.py#L56) looks a lot like that the code requires [Memory Synchronization](https://zugbruecke.readthedocs.io/en/latest/memsync.html) (`memsync`) directives.

**Comment by ghost** [comment]
Thank you. I'm not familiar with native code, so it's a bit more difficult for me, but I'll try to implement it while looking at the documentation!
